version: '3'

services:
  backend-app:
    container_name: react-graphql-events
    restart: always
    build: ./backend
    ports:
      - '80:3000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'